# Generated by Django 5.0.6 on 2024-05-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametouser',
            name='username',
            field=models.CharField(default='默认名字', max_length=100),
        ),
    ]
